C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/shader.vert -o src/GLSL/spv/vert.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/shader.frag -o src/GLSL/spv/frag.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Simulation.comp -o src/GLSL/spv/Simulation.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Boids.comp -o src/GLSL/spv/Boids.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/InsertionSort.comp -o src/GLSL/spv/InsertionSort.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Reduce.comp -o src/GLSL/spv/Reduce.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/MapAgentToMaxX.comp -o src/GLSL/spv/MapAgentToMaxX.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/MapAgentToCurrentX.comp -o src/GLSL/spv/MapAgentToCurrentX.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/MapXToAgent.comp -o src/GLSL/spv/MapXToAgent.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/CollisionDetection.comp -o src/GLSL/spv/CollisionDetection.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/AdvanceTime.comp -o src/GLSL/spv/AdvanceTime.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Impact.comp -o src/GLSL/spv/Impact.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Scan.comp -o src/GLSL/spv/Scan.spv
