C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/shader.vert -o src/GLSL/vert.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/shader.frag -o src/GLSL/frag.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Simulation.comp -o src/GLSL/Simulation.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/InsertionSort.comp -o src/GLSL/InsertionSort.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Reduce.comp -o src/GLSL/Reduce.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/MapAgentToX.comp -o src/GLSL/MapAgentToX.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/MapXToAgent.comp -o src/GLSL/MapXToAgent.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/CollisionDetection.comp -o src/GLSL/CollisionDetection.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/AdvanceTime.comp -o src/GLSL/AdvanceTime.spv
C:/VulkanSDK/1.2.141.2/Bin32/glslc.exe src/GLSL/Impact.comp -o src/GLSL/Impact.spv
