#version 460
#extension GL_ARB_separate_shader_objects : enable

#define X_DIM 512

layout (local_size_x = X_DIM, local_size_y = 1, local_size_z = 1) in;

struct AgentRenderInfo {
    uint typeId;
    vec3 position;
    vec4 rotation;
};

struct ValueAndIndex {
    uint value;
    uint index;
};

readonly layout (std430, binding = 0) buffer agentsInBuffer {
    AgentRenderInfo agentsIn[];
};

readonly layout (std430, binding = 1) buffer valueAndIndexesBuffer {
    ValueAndIndex valueAndIndexes[];
};

writeonly layout (std430, binding = 2) buffer agentsOutBuffer {
    AgentRenderInfo agentsOut[];
};

readonly layout (std430, binding = 3) buffer numberOfElementsBuffer {
    uint numberOfElements;
};

void main() {
    const uint index = gl_GlobalInvocationID.x;

    if (index >= numberOfElements) { return; }

    agentsOut[index] = agentsIn[valueAndIndexes[index].index];
}
