#version 460
#extension GL_ARB_separate_shader_objects : enable

#define X_DIM 512

layout (local_size_x = X_DIM, local_size_y = 1, local_size_z = 1) in;

struct AgentRenderInfo {
    uint typeId;
    vec3 position;
    vec4 rotation;
};

readonly layout (std430, binding = 0) buffer agentsBuffer {
    AgentRenderInfo agents[];
};

writeonly layout (std430, binding = 1) buffer offsetsBuffer {
    uint offsets[];
};

readonly layout (std430, binding = 2) buffer numberOfElementsBuffer {
    uint numberOfElements;
};

void main() {
    const uint index = gl_GlobalInvocationID.x;

    if (index >= numberOfElements) { return; }

    AgentRenderInfo agent = agents[index];

    if ((index == 0) || (agents[index - 1].typeId != agent.typeId)) {
        offsets[agent.typeId] = index;
    }
}
