#version 460
#extension GL_ARB_separate_shader_objects : enable

#define X_DIM 256

layout (local_size_x = X_DIM, local_size_y = 1, local_size_z = 1) in;

struct Agent {
    int typeId;
    int playerId;
    vec3 position;
    vec3 velocity;
    vec3 acceleration;
    vec3 target;
    vec3 rotationalVelocity;
    vec4 rotation;
    float radius;
};

struct ValueAndIndex {
    float value;
    uint index;
};

layout (std430, binding = 0) buffer bufferValueAndIndex {
    ValueAndIndex valueAndIndexes[];
};

layout (std430, binding = 1) buffer bufferAgentIn {
    Agent agentsIn[];
};

layout (std430, binding = 2) buffer bufferAgentOut {
    Agent agentsOut[];
};

layout (std430, binding = 3) buffer bufferNumberOfElements {
    uint numberOfElements;
};

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= numberOfElements) { return; }

    uint agentIndex = valueAndIndexes[index].index;

    agentsOut[index] = agentsIn[agentIndex];
}
